---
# This playbook is run from packer during kickstart (phase 1)
- hosts: 127.0.0.1
  user: vagrant
  sudo: yes

- include: rhel6.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int <= 7

- include: fedora.yml
  when: ansible_distribution == 'Fedora'
