#!/usr/bin/env ansible-playbook
# This playbook is run as a provisioner for vagrant
### centos7
- hosts: centos7
  user: vagrant
  become: yes

  roles:
    - loghost
    - RHEL7-CIS

- hosts: cloud
  become: yes

  roles:
    - cis_audit

### centos6
#- hosts: centos6
#  user: vagrant
#  become: yes

#  vars_files:
#    - "group_vars/centos6"

#  roles:
#    - { role: RHEL6-STIG, rhel6stig_cat2: true, rhel6stig_cat3: true, rhel6stig_is_mail_relay: true }


### Ubuntu
- name: bootstrap ubuntu hosts
  hosts: ubuntu
  gather_facts: True
  become: yes

  vars_files:
    - "group_vars/ubuntu"

  pre_tasks:
    - include: tasks/dockpack.yml

  roles: []

  tasks:
    - include: tasks/dockpack.yml

### fedora
- name: bootstrap fedora hosts
  hosts: fedora
  gather_facts: True
  become: yes
  roles:
    - loghost


- name: bootstrap coreos hosts
  hosts: coreos
  gather_facts: False

  vars_files:
    - "group_vars/coreos"

  roles:
    - defunctzombie.coreos-bootstrap
