---
# This playbook is run as a provisioner for vagrant
- hosts: centos6
  user: vagrant
  sudo: yes

  roles:
    - issue
    - loghost

- name: bootstrap ubuntu hosts
  hosts: ubuntu
  gather_facts: True
  sudo: yes

  roles:
    - geerlingguy.java

- name: bootstrap fedora hosts
  hosts: fedora21
  gather_facts: True
  sudo: yes

  tasks:
     include: tasks/install_docker.yml

- name: bootstrap coreos hosts
  hosts: coreos
  gather_facts: False

  roles:
    - defunctzombie.coreos-bootstrap

- name: bootstrap rancheros hosts
  hosts: rancheros
  gather_facts: False
  sudo: yes

  tasks:
     include: tasks/bootstrap_rancheros.yml
