---
# This playbook is run as a provisioner for vagrant
- hosts: centos6
  user: vagrant
  sudo: yes

  vars_files:
    - "group_vars/centos6"

  roles:
    - issue
    - loghost

- name: bootstrap ubuntu hosts
  hosts: ubuntu
  gather_facts: True
  sudo: yes

  vars_files:
    - "group_vars/ubuntu"
  roles:
    - geerlingguy.java

- name: bootstrap fedora hosts
  hosts: fedora21
  gather_facts: True
  sudo: yes

  tasks:
     include: tasks/install_docker.yml

- name: bootstrap coreos hosts
  hosts: coreos
  gather_facts: False

  vars_files:
    - "group_vars/coreos"

  roles:
    - defunctzombie.coreos-bootstrap
